apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
    release: release2
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30020
  type: NodePort

