apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
    release: release2
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

